-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Szkarson.

module Szkarson.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Szkarson.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Szkarson.Abs.Ident where
  prt _ (Szkarson.Abs.Ident i) = doc $ showString i
instance Print (Szkarson.Abs.Prog' a) where
  prt i = \case
    Szkarson.Abs.Program _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (Szkarson.Abs.TopDef' a) where
  prt i = \case
    Szkarson.Abs.FnDef _ id_ args type_ block -> prPrec i 0 (concatD [doc (showString "fn"), prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])
    Szkarson.Abs.GlobDecl _ type_ items -> prPrec i 0 (concatD [doc (showString "global"), prt 0 type_, prt 0 items, doc (showString ";")])

instance Print [Szkarson.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Szkarson.Abs.Arg' a) where
  prt i = \case
    Szkarson.Abs.VArg _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])

instance Print [Szkarson.Abs.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Szkarson.Abs.Block' a) where
  prt i = \case
    Szkarson.Abs.BBlock _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print (Szkarson.Abs.Decl' a) where
  prt i = \case
    Szkarson.Abs.DDecl _ type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    Szkarson.Abs.FnDecl _ id_ args type_ block -> prPrec i 0 (concatD [doc (showString "fn"), prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])

instance Print [Szkarson.Abs.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Szkarson.Abs.Stmt' a) where
  prt i = \case
    Szkarson.Abs.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    Szkarson.Abs.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    Szkarson.Abs.DStmt _ decl -> prPrec i 0 (concatD [prt 0 decl])
    Szkarson.Abs.Ass _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    Szkarson.Abs.Incr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    Szkarson.Abs.Decr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    Szkarson.Abs.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Szkarson.Abs.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Szkarson.Abs.SIf _ expr block elseifs -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 block, prt 0 elseifs])
    Szkarson.Abs.SIfElse _ expr block1 elseifs block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 block1, prt 0 elseifs, doc (showString "else"), prt 0 block2])
    Szkarson.Abs.While _ expr block -> prPrec i 0 (concatD [doc (showString "while"), prt 0 expr, prt 0 block])
    Szkarson.Abs.Break _ -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    Szkarson.Abs.Continue _ -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    Szkarson.Abs.Print _ exprs -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 exprs, doc (showString ")"), doc (showString ";")])
    Szkarson.Abs.Assert _ expr -> prPrec i 0 (concatD [doc (showString "assert"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
    Szkarson.Abs.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (Szkarson.Abs.Item' a) where
  prt i = \case
    Szkarson.Abs.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    Szkarson.Abs.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print [Szkarson.Abs.Item' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Szkarson.Abs.ElseIf' a) where
  prt i = \case
    Szkarson.Abs.ElIf _ expr block -> prPrec i 0 (concatD [doc (showString "elif"), prt 0 expr, prt 0 block])

instance Print [Szkarson.Abs.ElseIf' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Szkarson.Abs.Type' a) where
  prt i = \case
    Szkarson.Abs.TInt _ -> prPrec i 0 (concatD [doc (showString "int")])
    Szkarson.Abs.TStr _ -> prPrec i 0 (concatD [doc (showString "string")])
    Szkarson.Abs.TBool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    Szkarson.Abs.TVoid _ -> prPrec i 0 (concatD [doc (showString "void")])

instance Print (Szkarson.Abs.Expr' a) where
  prt i = \case
    Szkarson.Abs.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    Szkarson.Abs.EBuildInFun _ id_1 id_2 exprs -> prPrec i 6 (concatD [prt 0 id_1, doc (showString "."), prt 0 id_2, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Szkarson.Abs.EAddr _ id_ -> prPrec i 6 (concatD [doc (showString "&"), prt 0 id_])
    Szkarson.Abs.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    Szkarson.Abs.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    Szkarson.Abs.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    Szkarson.Abs.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Szkarson.Abs.EString _ str -> prPrec i 6 (concatD [printString str])
    Szkarson.Abs.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Szkarson.Abs.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    Szkarson.Abs.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Szkarson.Abs.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Szkarson.Abs.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Szkarson.Abs.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    Szkarson.Abs.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])

instance Print [Szkarson.Abs.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Szkarson.Abs.AddOp' a) where
  prt i = \case
    Szkarson.Abs.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    Szkarson.Abs.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (Szkarson.Abs.MulOp' a) where
  prt i = \case
    Szkarson.Abs.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    Szkarson.Abs.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    Szkarson.Abs.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (Szkarson.Abs.RelOp' a) where
  prt i = \case
    Szkarson.Abs.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    Szkarson.Abs.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    Szkarson.Abs.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    Szkarson.Abs.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    Szkarson.Abs.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    Szkarson.Abs.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])
